"""download link field

Revision ID: a99e6a7a9c6f
Revises: fad2fa9eb3d7
Create Date: 2025-07-29 13:16:55.211269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99e6a7a9c6f'
down_revision = 'fad2fa9eb3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies_series', schema=None) as batch_op:
        batch_op.drop_column('download_link')

    # ### end Alembic commands ###
