"""update watchlists table

Revision ID: f6a37873c5c0
Revises: 5488369f234b
Create Date: 2025-07-26 17:16:48.529604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a37873c5c0'
down_revision = '5488369f234b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_series_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_series_id'], ['movies_series.id']),
    sa.ForeignKeyConstraint(['user_id'], ['users.id']),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlists')
    # ### end Alembic commands ###
