"""payments table

Revision ID: f9ac18f37fd7
Revises: f6a37873c5c0
Create Date: 2025-07-28 01:00:02.432535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ac18f37fd7'
down_revision = 'f6a37873c5c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('movie_series_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('added_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['movie_series_id'], ['movies_series.id'], name='fk_watchlists_movie_series_id_movies_series'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_watchlists_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
